### ISSUE TITLE
Add additional validation rules

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#3]
Each of these rules should implement the `Rule` interface, and have a test to validate it works as expected. Keep in mind that Tempest relies on PHP's type system for rudimentary validation like required, nullable, and type. These shouldn't be validation rules.

- [x] Alpha - all characters are letters [A-Za-z] (https://github.com/tempestphp/tempest-framework/pull/69)
- [x] AlphaNumeric - all characters are alphanumeric (https://github.com/tempestphp/tempest-framework/pull/69)
- [x] Count — an array with a min/max count
- [x] Email — a valid email address
- [x] Enum — a valid enum value (#68)
- [x] Length — a string with a min/max length
- [x] PhoneNumber — a valid phone number
- [x] Between — an integer between two values, edges included
- [x] Boolean (https://github.com/tempestphp/tempest-framework/pull/76)
- [x] ShouldBeTrue — a value that represents a boolean `true` value. (#64)
- [x] ShouldBeFalse — a value the represents a boolean `false` value (#64)
- [x] Url — a valid URL
- [ ] ~Date — a valid date~ we can use DateTimeFormat?
- [x] Time — a valid time (#67)
- [x] DateTimeFormat — a valid date/date time with a specific format (#53)
- [x] Timestamp — a valid timestamp (integer)
- [x] Timezone - a valid timezone
- [x] Regular Expression — value matches the regular expression passed (#72)
- [x] StartsWith - starts with the specified string (https://github.com/tempestphp/tempest-framework/pull/74)
- [x] EndsWith - ends with the specified string (#82)
- [x] DoesNotStartWith - does not start with the specified string
- [x] DoesNotEndWith - does not end with the specified string
- [x] Uppercase - is UPPERCASE (#82)
- [x] Lowercase - is lowercase (#82)
- [x] UUID - is a valid UUID
- [x] ULID - is a valid ULID
- [x] IP Address - is a valid IP address
- [x] MAC Address - is a valid MAC address
- [x] Password - Allows the specification of password complexity with some sensible defaults
- [ ] ~PasswordNotCompromised - Checks the password against haveibeenpwned~ not right now
- [ ] ~SameAs — this value should be the same as another value, for example for password validation~ skip for now since Rules aren't aware of their larger context.

**Comment by aidan-casey** [comment]
@brendt - it might be helpful to flesh out exactly which rules we'd need to see in place before v1. Gives people something to work toward. 🙂

**Comment by brendt** [comment]
I'll draft a list later today or tomorrow :)

**Comment by aidan-casey** [comment]
@brendt - I'm thinking we should update the rule interface to simply accept the object under validation as an additional parameter. Any reason you can think of not to do this vs. something like a separate data aware interface like Laravel has?

**Comment by brendt** [comment]
Do you have an example of when it might be useful? My intention for validation rules was that they would be an extension on PHP's type system without the need for any additional context. But I'm open for exploring alternatives

**Comment by aidan-casey** [comment]
The `SameAs` rule will require the greater context of the object, unless you want to engage wizardry mode.

**Comment by aidan-casey** [comment]
@brendt - I am going to expand your list every time we get close to finishing it. 😉

**Comment by brendt** [comment]
Btw, if `SameAs` is the only rule that requires context, then we should skip it for now. There are other solutions to solving it which are convenient enough.

**Comment by aidan-casey** [comment]
Alpha / AlphaNumeric were added in #69.

**Comment by aidan-casey** [comment]
@brendt - should Tempest be supporting conditional validation rules?

For example, if I want the value to be a URL OR IP address?

**Comment by brendt** [comment]
Not right now, I don't think it's needed for 1.0.

**Comment by omerimzali** [comment]
@brendt  PasswordNotCompromised - Checks the password against haveibeenpwned
For this validation rule are you planning to send a request to haveibeenpwned? Or is there another solution to this issue, such as searching through a local list?  If we need to make the request, would curl be appropriate? Or would you consider using Guzzle? The project has not used either of them before.

**Comment by brendt** [comment]
I believe it's indeed a request to haveibeenpwned. We can always look at how Laravel and Symfony implement those rules, to be sure.

The question about which HTTP client to use is actually an interesting one. I'm sure we shouldn't use curl directly, so maybe guzzle; but I really dislike the overhead that comes with PSR support in guzzle. Maybe let's not work on this rule until we've figured out which HTTP client we want to use throughout Tempest.

**Comment by omerimzali** [comment]
Would you consider doing Msisdn validation? Phone numbers are as commonly used as email. I'd like to create that validation, If you consider to add.

**Comment by aidan-casey** [comment]
@omerimzali I believe this is covered by the PhoneNumber rule, no?

**Comment by aidan-casey** [comment]
@omerimzali - Perfect! I will try to remember mentioning MSISDN in the docs so it is easily searchable. 🙂

**Comment by aidan-casey** [comment]
> I believe it's indeed a request to haveibeenpwned

See more details [here](https://haveibeenpwned.com/API/v3#PwnedPasswords) on the API for checking password hashes.

> Maybe let's not work on this rule until we've figured out which HTTP client we want to use throughout Tempest.

I think this is an accurate thought. 🙂

**Comment by brendt** [comment]
I think this one is ready to be closed 🥳 Thanks a lot to everyone helping out!
